name: Enable Compute Engine API

on:
  push:
    branches:
      - main
          
env:
  PROJECT_ID: airy-shadow-473609-h1
  GCP_SERVICE_ACCOUNT: ShaKar

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  enable_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/31127017233/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID'
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Enable Compute Engine API
        run: gcloud services enable compute.googleapis.com --project ${{ env.PROJECT_ID }}
