name: Enable Compute Engine API on Push

on:
  push:
    branches:
      - main

# REQUIRED: Grant the runner permissions to request the OIDC token
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  enable_compute_api:
    runs-on: ubuntu-latest
    
    # Environment variables
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (Impersonate Service Account)
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # Use the WIF Provider secret to establish trust
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          # The Service Account created in Step 2 with the 'Service Usage Admin' role
          service_account: github-enabler@${{ env.GCP_PROJECT }}.iam.gserviceaccount.com
          # This sets up the gcloud CLI and authentication automatically
          setup_gcloud: true 

      - name: Enable Compute Engine API
        id: enable_api
        # The gcloud command to enable the API
        run: |
          echo "Attempting to enable compute.googleapis.com in project: ${{ env.GCP_PROJECT }}"
          
          # The command is idempotent: safe to run even if already enabled
          gcloud services enable compute.googleapis.com --project="${{ env.GCP_PROJECT }}"
          
          echo "Compute Engine API enabled successfully."
