name: My Manual Workflow

on:
  workflow_dispatch:   # 👈 This enables manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "Hello, this workflow was triggered manually!"
