name: CI

on:
  push:          # Trigger on push
    branches: 
      - main     # or your default branch
  pull_request:  # Also trigger on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest   # Runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'       # Choose Node version

      - name: Install dependencies
        run: npm install           # or yarn install

      - name: Run tests
        run: npm test   
